### ISSUE TITLE
Paginate with Nested Scroll View?

### ISSUE THREAD

**Issue by milen-3web** [MarkoMilos/Paginate#22] opened 2016-11-16 07:16 UTC
Hello, Marko. Thank you very much for the great lib. It's working great for me and you save me a lot of time and effort. I have two fragments. In the first one I have a recycle view only and I use Paginate and it works just great. In the second fragment I have a Nested scroll view like this:

```
<android.support.v4.widget.NestedScrollView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/profileBg">

                <android.support.v7.widget.RecyclerView android:id="@+id/list"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:overScrollMode="never"
                    android:background="@color/profileBg"
                    xmlns:android="http://schemas.android.com/apk/res/android" />

            </LinearLayout>

    </android.support.v4.widget.NestedScrollView>

        -------------------------------------------------------------------------------------------


        LinearLayoutManager layoutManager = new LinearLayoutManager(mContext);
        layoutManager.setAutoMeasureEnabled(true);

        adapter = new PostAdapter(mContext, posts, this);

        list.setLayoutManager(layoutManager);
        list.setNestedScrollingEnabled(false);
        list.addItemDecoration(new SpacesItemDecoration((int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 5, mContext.getResources().getDisplayMetrics())));
        list.setAdapter(adapter);

        callbacks = new Paginate.Callbacks() {
            @Override
            public void onLoadMore() {
                loading = true;
                OFFSET += LIMIT;

                loadNextDataFromApi(OFFSET);
            }

            @Override
            public boolean isLoading() {
                return loading;
            }

            @Override
            public boolean hasLoadedAllItems() {
                return false;
            }
        };

        paginate = Paginate.with(list, callbacks)
                .setLoadingTriggerThreshold(8)
                .build();
```

I also tried without: 
 ```
layoutManager.setAutoMeasureEnabled(true);
 list.setNestedScrollingEnabled(false);
```
but the result is the same. I use the same logic in the two places but when it's in the nested scroll view scrolling becomes really slow and finally app just stop working. Without the Paginate it's work fine. Do you have any suggestions for this bug? Thank you very much!

**Update**: I set a break point and found that with  NestedScrollView it enters in the callback infinity times even without scrolling. I hope this can help you finding the problem.

**Update 2**: The same problem when embedded in a CordinatorLayout.

**Comment by MarkoMilos** [comment] 2016-11-18 11:06
@milen-3web thanks for the feedback... 
I will look into this issue and test the lib with `NestedScrollView` and `CordinatorLayout`. Can't tell atm what could cause this issue but both NestedSV and CordinatorL are intercepting and messing with touch (scroll events) and I will start from there.

**Comment by milen-3web** [comment] 2017-01-06 10:55
@MarkoMilos do you have any progress on this?

**Comment by viestursGr** [comment] 2017-02-12 14:32
I am also looking forward to resolution of this issue. I have NestedScrollView and CoordinatorLayout as well.

**Comment by 4lfant** [comment] 2017-03-03 16:51
I had the same problem and found the solution. 
Replace your NestedScrollView with LinearLayout like that:

```
<LinearLayout
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            app:layout_behavior="@string/appbar_scrolling_view_behavior">

            <android.support.v7.widget.RecyclerView
                  android:layout_width="match_parent"
                  android:layout_height="match_parent"
                  android:id="@+id/recycler_view"/>
</LinearLayout>
```

Don't forget to add `app:layout_behavior="@string/appbar_scrolling_view_behavior"` to attributes!

If you use RecyclerView inside NestedScrollView, layout manager can't measure it's height and set it infinite. So paginate will load data until all will be loaded even if you won't scroll the list.
With linear layout the height is measured and paginate will load data only if you scroll to the bottom of list.

**Comment by prossik** [comment] 2017-03-14 21:09
@4lfant your solution works, but what I'll need to do if I need NestedScrollView and Coordinator layouts ? :(

**Comment by 4lfant** [comment] 2017-03-18 17:45
@prossik why do you need exactly NestedScrollView? In my solution CoordinatorLayout remains the same and NestedScrollView is just replaced with LinearLayout, so the structure of your layout doesn't change and you can put there the list and all other items you need. Besides, LinearLayout behaves the same as NestedScrollView.

**Comment by minas1** [comment] 2017-09-11 10:34
@4lfant Solved it for me, thank you very much!

**Comment by DEV-NEP** [comment] 2017-11-10 05:15
Is this issue solved?? I am also facing problems using pagination in NestedScrollView.

**Comment by abayomiAkanji** [comment] 2018-07-25 02:49
@4lfant one might need a NestedScrollView if you have more than a RecyclerView on a Layout and you want them to scroll simultaneously.

In such scenario, how does one fix the pagination issue?

**Comment by SrishtiRoy** [comment] 2019-01-08 03:18
is this issue solved?

**Comment by ParryPatel021** [comment] 2019-04-09 11:24
> I had the same problem and found the solution.
> Replace your NestedScrollView with LinearLayout like that:
> 
> ```
> <LinearLayout
>             xmlns:app="http://schemas.android.com/apk/res-auto"
>             android:layout_width="match_parent"
>             android:layout_height="wrap_content"
>             android:orientation="vertical"
>             app:layout_behavior="@string/appbar_scrolling_view_behavior">
> 
>             <android.support.v7.widget.RecyclerView
>                   android:layout_width="match_parent"
>                   android:layout_height="match_parent"
>                   android:id="@+id/recycler_view"/>
> </LinearLayout>
> ```
> Don't forget to add `app:layout_behavior="@string/appbar_scrolling_view_behavior"` and ` android:layout_height="wrap_content"` to attributes!
> 
> If you use RecyclerView inside NestedScrollView, layout manager can't measure it's height and set it infinite. So paginate will load data until all will be loaded even if you won't scroll the list.
> With linear layout the height is measured and paginate will load data only if you scroll to the bottom of list.

You are right, @4lfant I am facing this problem in my app.  _If you use RecyclerView inside NestedScrollView, layout manager can't measure its height and set it infinite. So paginate will load data until all will be loaded even if you won't scroll the list._

Do you have any idea about how can I implement Scrolling and Recyclerview both in Single layout?
Thanks
>

**Comment by technyx-ali-rehman** [comment] 2019-04-15 09:00
Any solution for this issue yet ?

**Comment by khloudalmasri** [comment] 2019-12-09 07:37
Any solution for this issue yet ?

**Comment by bhupalreddykokkanti** [comment] 2019-12-21 11:33
Any solutions yet?

**Comment by shubham0728** [comment] 2019-12-31 10:24
Any solutions for this yet?

**Comment by MomenZaq** [comment] 2020-03-23 22:39
Any solutions for this yet?

**Comment by saddahussain** [comment] 2020-03-25 15:03
Here scroll is nested scroll view.
`scroll.getViewTreeObserver().addOnScrollChangedListener(() -> {
                View view = (View) scroll.getChildAt(scroll.getChildCount() - 1);

                Log.d("CategoryNeswList", scroll.getChildCount() + " child");
                int diff = (view.getBottom() - (scroll.getHeight() + scroll
                        .getScrollY()));

                if (diff == 0) {
//                        getPlaylistFromServer("more");
                    Toast.makeText(mContext, "Load More", Toast.LENGTH_SHORT).show();
                }
            });`

set scroll listener on nestedScrollView instead of recyclerview

**Comment by allefsousa** [comment] 2020-05-13 13:03
Same problem here, someone solution to use NestedScrollView + Paging Library ?

**Comment by ola-skorp** [comment] 2020-07-29 08:12
I solved the same problem by using one RecyclerView with ConcatAdapter from androidx.recyclerview:recyclerview:1.2.0-alpha05 instead of using two RecyclerViews inside NestedScrollView.
`recyclerView.adapter = ConcatAdapter(firstAdapter, secondAdapter)`

**Comment by jsdeyro** [comment] 2020-08-18 06:14
> Here scroll is nested scroll view.
> `scroll.getViewTreeObserver().addOnScrollChangedListener(() -> { View view = (View) scroll.getChildAt(scroll.getChildCount() - 1); Log.d("CategoryNeswList", scroll.getChildCount() + " child"); int diff = (view.getBottom() - (scroll.getHeight() + scroll .getScrollY())); if (diff == 0) { // getPlaylistFromServer("more"); Toast.makeText(mContext, "Load More", Toast.LENGTH_SHORT).show(); } });`
> 
> set scroll listener on nestedScrollView instead of recyclerview

Are you using paging 3 library for this? I tried using in paging 3 and still not working

**Comment by MarkoMilos** [comment] 2020-09-12 16:53
This is not an issue with the library. RecyclerViews are not meant to be placed inside scroll containers (e.g. `NestedScrollView`) with the same scroll direction. The view recycling only works when the height is set to `MATCH_PARENT`.

The problem is that measure spec `UNSPECIFIED` is passed down to `RecyclerView` and all items are rendered meaning that RecylcerView is not doing recycling.

You can verify that if you remove the Paginate library completely and assert that onBindViewHolder is called for each item on the data set (e.g. 100 items) even though only a small subset of them are actually visible on the screen.

You can achieve your goal with a few other options: 

1. Having adapter with multiple view types (headers/footers)
2. Using `RecyclerView` + `CoordinatorLayout` to apply scroll behavior for `Toolbar`/`TabLayout`.

Closing this issue.

**Closed by MarkoMilos** 2020-09-12 16:53 UTC
Labels: bug

**Comment by mohammedelnady** [comment] 2021-03-23 11:24
reopen again still a big issue

**Comment by valentynapolienova** [comment] 2025-11-13 16:43
Hi! Found another solution. **Don't provide any external scroll controller** to the `NestedScrollView` or `CustomScrollView`. Use the NestedScrollView's inner controller:

```
final _nestedKey = GlobalKey<NestedScrollViewState>();

// ...
return NestedScrollView(
  key: _nestedKey,
  // ...
);

// then in build:
final innerController = _nestedKey.currentState?.innerController;

FavouriteQuotesTab(
  controller: innerController!, // use this for pagination
),
```
