### ISSUE TITLE
Adapter issue

### ISSUE THREAD

**Issue by RaviUmraliya** [MarkoMilos/Paginate#39] opened 2018-08-27 10:55 UTC
if list is empty and i add the manually item in list and notify the adapter so pagination call and list will show double item

**Comment by MarkoMilos** [comment] 2020-09-14 12:08
I cannot reproduce this issue and I don't have any information about your setup.

I'm closing this. Feel free to reopen the ticket with a detailed explanation stating:
1. Your pagination setup (Recycler vs AbsListview)
2. Example code/project
3. Explanation when are you adding an item, during the loading, before, after what is returned from Paginate.Callback at that time.
4. How do you notify adapter

**Closed by MarkoMilos** 2020-09-14 12:08 UTC
