### ISSUE TITLE
OnLoadMore calls 2 times for the first time

### ISSUE THREAD

**Issue by abumoallim** [MarkoMilos/Paginate#32] opened 2017-09-04 08:02 UTC

**Comment by mori-honest** [comment] 2017-12-11 07:30
Same problem here!
and also if you try to scroll fast (up and down) and get near to end of the list, you may get stuck into infinite load more!

**Comment by TrungNguyen1208** [comment] 2018-04-05 04:52
Anyone know to fix this? I have same problem?

**Comment by hailongren** [comment] 2019-01-08 02:38
> Same problem here!
> and also if you try to scroll fast (up and down) and get near to end of the list, you may get stuck into infinite load more!
Same issue .  Do you find the solution?

**Comment by necavit** [comment] 2019-05-15 08:26
The problem is that the library calls `checkEndOffset()` twice: first, upon initialization (makes sense) and, second, when the RecyclerView's `onScrolled()` event takes place. Note that `onScrolled()` is being called with `dx` and `dy` equal to 0. This is due to RecyclerView calling the scroll listener when layout changes happen, even if no scroll was performed by the user.

I don't know if the bug is with this library or with RecyclerView calling the scroll event when it shouldn't (from my point of view, it's a really stupid design decision from the Android team).

So far, my solution has been to immediately set a member `isLoading` flag to true. This is the flag that the Paginate callback is returning.

**Comment by noecende** [comment] 2019-07-04 18:14
@necavit could you please explain a little bit more how to solve this? Where do you set the isLoadingFlag?

**Comment by yasirnaseem1990** [comment] 2019-12-11 01:53
@necavit could you please explain in which method you set the **isLoading** flag to true immediately?

**Comment by MarkoMilos** [comment] 2020-09-12 18:15
The truth is that `onLoadMore()` is called once on initialization and each time when `RecyclerView.OnScrollListener` calls `onScrolled(...)`.

However, before `onLoadMore()` is called the check is performed to assert that loading is not currently in progress by calling `Paginate.Callback`s `isLoading()` method.

If you return true here, even tough check is performed `onLoadMore()` won't be called. That said, the first time when `onLoadMore()` is called you need to set your flag (or however you are handling this) to true immediately in the main thread.

I'm closing this issue for now, please fill free to reopen it with a code example demonstrating the issue.

**Closed by MarkoMilos** 2020-09-12 18:15 UTC
