### ISSUE TITLE
Nested Scroll view Paginate request

### ISSUE THREAD

**Issue by alihabbash** [MarkoMilos/Paginate#38] opened 2018-08-16 12:11 UTC
Is there is any way to add support for nested scroll view as well 
So, the code will be 
`Paginate.with(nestedScrollView);`
as well as:
`Paginate.with(recyclerView);`

**Comment by MarkoMilos** [comment] 2020-09-12 16:56
This is a duplicate of #22

**Closed by MarkoMilos** 2020-09-12 16:56 UTC
Labels: duplicate

**Comment by mohammedelnady** [comment] 2021-03-23 11:25
Pagination repeated more and more with nestedscrollview

**Comment by ShineThyuZan** [comment] 2022-01-19 07:29
how can i solve pagination and nestedscrollview error?
