### ISSUE TITLE
return true on hasLoadedAllItems not working 

### ISSUE THREAD

**Issue by rchampa** [MarkoMilos/Paginate#23] opened 2016-11-20 19:52 UTC
I have the following code and loading row is still showing.
Why?
 ```
@Override
    public void onLoadMore() {
        Log.d("EncryptionPager","onLoadMore");

    }

    @Override
    public boolean isLoading() {
        Log.d("EncryptionPager","isLoading");
        return false;
    }

    @Override
    public boolean hasLoadedAllItems() {
        Log.d("EncryptionPager","hasLoadedAllItems");
        return true;
    }
```

**Comment by LiuJQ** [comment] 2016-11-23 03:19
Exactly, if you even has no one item.

**Comment by constantinoschristoforou** [comment] 2017-01-14 14:21
Any news about that?

**Comment by LiuJQ** [comment] 2017-01-19 13:05
you can call `unbind()` method to stop it

**Comment by 4lfant** [comment] 2017-03-03 15:41
Loading row hides only when setHasMoreDataToLoad() method is called.

From RecyclerPaginate.java:
```
@Override
public void setHasMoreDataToLoad(boolean hasMoreDataToLoad) {
        if (wrapperAdapter != null) {
        wrapperAdapter.displayLoadingRow(hasMoreDataToLoad);
    }
}
```


The problem is that it works only with WrapperAdapter.

So there are two solutions:
1. You create the list adapter which extends WrapperAdapter.
2. Or manually hide the loading row by calling paginate.setHasMoreDataToLoad(false);


In my case:

```
Paginate paginate = Paginate.with(recyclerView, new PaginateCallbacks())
                .setLoadingTriggerThreshold(0)
                .addLoadingListItem(true)
                .build();
```
And then in callbacks:
```
private class PaginateCallbacks implements Paginate.Callbacks {
        private boolean loading = false;

        @Override
        public void onLoadMore() {
            loading = true;
            RetrofitService.getClient().getData()
            .enqueue(new Callback<Data>() {
                        @Override
                        public void onResponse(Call<Data> call, Response<Data> response) {
                            if (response.isSuccessful()) {
                                if (response.body().isEmpty()) {
                                    paginate.setHasMoreDataToLoad(false);
                                    return;
                                }
                                data.addAll(response.body());
                                loading = false;
                                if (response.body().size() < DATA_PORTION_SIZE) {
                                    paginate.setHasMoreDataToLoad(false);
                                }
                            } else {
                                Log.e(TAG, response.errorBody());
                            }
                        }
                        @Override
                        public void onFailure(Call<Data> call, Throwable t) {
                              t.printStackTrace();
                        }
                    });
        }

        @Override
        public boolean isLoading() {
            return loading;
        }

        @Override
        public boolean hasLoadedAllItems() {
            /*
             Works only for WrapperAdapter. But we use our own RecyclerView.Adapter.
             So must manually call paginate.setHasMoreDataToLoad(false)
              */
            return false;
        }
    }
```

**Comment by MarkoMilos** [comment] 2020-09-23 18:12
This has been resolved as a part of the latest release (check out release 1.0.0)

I'm closing this MR, feel free to reopen if you still experiencing this issue.

**Closed by MarkoMilos** 2020-09-23 18:12 UTC
Labels: bug
